In [1]:
import numpy as np

In [2]:
# https://numpy.org/

## numpy array

In [3]:
my_list = [10,20,30,40,50]
type(my_list)

list

In [4]:
print(type(np.array(my_list)))
np.array(my_list)

<class 'numpy.ndarray'>


array([10, 20, 30, 40, 50])

In [5]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange

In [6]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

## zeros & ones

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## linspace & eye

In [13]:
np.linspace(0,10,30)

# 0 dan 10 a kadar git, elemanlar arasındaki farkın eşit olduğu array

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [14]:
# birim matris 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [15]:
# normal dağılıma uygun veriler çıkartır.
np.random.randn(4)

array([ 1.22323087,  0.21154274, -0.48553352, -1.22589291])

In [16]:
np.random.rand(4,4)

array([[0.52109043, 0.84625321, 0.53850603, 0.15729611],
       [0.2196807 , 0.05173178, 0.96188774, 0.12877326],
       [0.71030418, 0.13489608, 0.64374094, 0.54110212],
       [0.04496397, 0.75042551, 0.09057477, 0.59542226]])

In [17]:
np.random.randint(1,20)

9

In [18]:
np.random.randint(1,300,5)

array([224, 202,  68, 238, 203], dtype=int32)

In [19]:
np_list = np.arange(12)
np_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np_random_list = np.random.randint(0,200,10)
np_random_list

array([  2, 185,  47,  22, 150, 193, 134, 188, 142,  79], dtype=int32)

## numpy array methods

In [21]:
np_list.reshape(3,4) # 3*4=12 -> len(np_list)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np_random_list.max()

np.int32(193)

In [23]:
np_random_list.min()

np.int32(2)

In [24]:
np_random_list.argmax() # [5] = 117

np.int64(5)

In [25]:
np_random_list.argmin() # [8] = 9

np.int64(0)

In [26]:
matrix = np_list.reshape(3,4)
matrix.shape

(3, 4)

## Index

In [27]:
benimDizim = np.arange(15)
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
print(benimDizim[5])
print()
print(benimDizim[1:4])
print()
print(benimDizim[0:10:2])

5

[1 2 3]

[0 2 4 6 8]


In [29]:
benimDizim[0:2] = -5
benimDizim

array([-5, -5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
slicing_dizisi = benimDizim[0:2]
slicing_dizisi

array([-5, -5])

In [31]:
slicing_dizisi[:] = 700
slicing_dizisi

array([700, 700])

In [32]:
benimDizim

array([700, 700,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [33]:
kopya = benimDizim.copy()
kopya

array([700, 700,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [34]:
kopya_slicing = kopya[0:2]
kopya_slicing

array([700, 700])

In [35]:
kopya_slicing[:] = 888
kopya_slicing

array([888, 888])

In [36]:
benimDizim

array([700, 700,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

## matrix

In [37]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
my_matrix[1][1]

np.int64(5)

In [39]:
my_matrix[1,1]

np.int64(5)

In [40]:
my_matrix[1:,2]

array([6, 9])

In [41]:
my_matrix[0:,2:]

array([[3],
       [6],
       [9]])

In [42]:
my_matrix[[2,0]]

array([[7, 8, 9],
       [1, 2, 3]])

## Operations

In [43]:
new_list = np.random.randint(0,100,20)
new_list

array([14, 90, 58, 90, 87, 60, 69, 85,  9, 77, 67, 58, 97, 99, 57, 74, 63,
       46, 91, 35], dtype=int32)

In [44]:
# 50' den büyükleri getir
new_list > 50

array([False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False])

In [45]:
new_list[new_list>50]

array([90, 58, 90, 87, 60, 69, 85, 77, 67, 58, 97, 99, 57, 74, 63, 91],
      dtype=int32)

In [46]:
last_array = np.arange(0,24)
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
last_array + last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [48]:
last_array - last_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [49]:
last_array * last_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [50]:
last_array / last_array

C:\Users\Ensar\AppData\Local\Temp\ipykernel_16036\3398326563.py:1: RuntimeWarning: invalid value encountered in divide
  last_array / last_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [51]:
np.sqrt(last_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [52]:
np.max(last_array)

np.int64(23)

In [53]:
np.min(last_array)

np.int64(0)